repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: check-docstring-first
      stages:
      - commit
      - push
    - id: check-merge-conflict
      stages:
      - push
    - id: double-quote-string-fixer
      stages:
      - commit
      - push
    - id: flake8
      stages:
      - commit
      - push
      args:
      - --max-line-length=120
    - id: trailing-whitespace
      stages:
      - commit
      - push
    - id: end-of-file-fixer
      stages:
      - commit
      - push
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    - id: autopep8
      stages:
        - commit
        - push
      args:
        - --max-line-length=120
        - --diff
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v1.4.1
    hooks:
    - id: add-trailing-comma
      stages:
        - commit
        - push
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    - id: mypy
